import type { SakeTag, SakeTagGroup } from "../types/sake";

type DefaultSakeTag = Pick<
  SakeTag,
  "id" | "owner_id" | "drink_type" | "tag_group" | "label" | "is_default"
>;

export const DEFAULT_SAKE_TAGS: ReadonlyArray<DefaultSakeTag> = [
  {
    id: "tag_taste_fresh",
    owner_id: null,
    drink_type: "sake",
    tag_group: "taste",
    label: "산뜻",
    is_default: true,
  },
  {
    id: "tag_taste_umami",
    owner_id: null,
    drink_type: "sake",
    tag_group: "taste",
    label: "감칠",
    is_default: true,
  },
  {
    id: "tag_taste_soft",
    owner_id: null,
    drink_type: "sake",
    tag_group: "taste",
    label: "부드러움",
    is_default: true,
  },
  {
    id: "tag_taste_rich",
    owner_id: null,
    drink_type: "sake",
    tag_group: "taste",
    label: "진함",
    is_default: true,
  },
  {
    id: "tag_taste_clean",
    owner_id: null,
    drink_type: "sake",
    tag_group: "taste",
    label: "깔끔함",
    is_default: true,
  },
  {
    id: "tag_taste_bitter",
    owner_id: null,
    drink_type: "sake",
    tag_group: "taste",
    label: "쌉쌀함",
    is_default: true,
  },
  {
    id: "tag_taste_sweet",
    owner_id: null,
    drink_type: "sake",
    tag_group: "taste",
    label: "달콤함",
    is_default: true,
  },
  {
    id: "tag_aroma_koji",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "누룩",
    is_default: true,
  },
  {
    id: "tag_aroma_rice",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "쌀",
    is_default: true,
  },
  {
    id: "tag_aroma_fruit",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "과일",
    is_default: true,
  },
  {
    id: "tag_aroma_flower",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "꽃",
    is_default: true,
  },
  {
    id: "tag_aroma_apple",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "사과",
    is_default: true,
  },
  {
    id: "tag_aroma_pineapple",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "파인애플",
    is_default: true,
  },
  {
    id: "tag_aroma_melon",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "멜론",
    is_default: true,
  },
  {
    id: "tag_aroma_pear",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "배",
    is_default: true,
  },
  {
    id: "tag_aroma_herb",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "허브",
    is_default: true,
  },
  {
    id: "tag_aroma_yogurt",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "요구르트",
    is_default: true,
  },
  {
    id: "tag_aroma_nut",
    owner_id: null,
    drink_type: "sake",
    tag_group: "aroma",
    label: "견과",
    is_default: true,
  },
  {
    id: "tag_mood_unique",
    owner_id: null,
    drink_type: "sake",
    tag_group: "mood",
    label: "독특",
    is_default: true,
  },
  {
    id: "tag_mood_easy",
    owner_id: null,
    drink_type: "sake",
    tag_group: "mood",
    label: "무난",
    is_default: true,
  },
  {
    id: "tag_mood_food",
    owner_id: null,
    drink_type: "sake",
    tag_group: "mood",
    label: "안주랑 먹기 좋음",
    is_default: true,
  },
  {
    id: "tag_mood_aperitif",
    owner_id: null,
    drink_type: "sake",
    tag_group: "mood",
    label: "식전주",
    is_default: true,
  },
] as const;

export function getDefaultSakeTagsByGroup(tagGroup: SakeTagGroup) {
  return DEFAULT_SAKE_TAGS.filter((tag) => tag.tag_group === tagGroup);
}
